### ISSUE TITLE
Auth problems?

### ISSUE THREAD

**Issue by ChrisK1994** [andrechristikan/ack-nestjs-boilerplate-mongoose#354]
I freshly started this app but can't get auth mechanism to work. 

Login is fine so I take the accessToken from 'admin' login action and paste it in the accessToken on swagger for GET b/api/v1/admin/role/list
![image](https://user-images.githubusercontent.com/26569213/211196760-60f2a990-fe8d-496e-aae4-b9f29fc6e89a.png)

But then I get an error 
`"statusCode": 5102,
    "message": "auth.error.permissionTokenUnauthorized",
    "error": "auth.error.permissionTokenUnauthorized"`

When I set 'x-permission-token' header I get:
`"statusCode": 5106,
    "message": "Permission not allowed",
    "error": "auth.error.permissionForbidden"`

So how to make it work?

**Comment by andrechristikan** [comment]
Okay got it, 
That because i forgot to update the swagger.

Sorry for that, i will fix it

**Comment by andrechristikan** [comment]
Now all permission with `/admin` prefix will protected with 2 token.
1. Access Token : `/login`
2. Permission Token `/grant-permission`
 
So... after you get the access token (authenticate), then you must to claim `permission token` (authorize).

**Comment by ChrisK1994** [comment]
Why do we need two functions? Isn't it enough just to /login? 
Like, since you have the accessToken you can generate permission token anyway, so it's not more secure just more boilerplate?

**Comment by andrechristikan** [comment]
That not for security reason. That approach for reduce the size of token payload.

I want build this boilerplate to keep stateleas for user authentication and authorization. So i consume jwt as access token and put all permission related user in the payload. Because of that, the previous payload has a huge bytes and got rejected by aws api gateway. Also, previous approach will break time of execution.

In my real case
I have more than 100 permissions included read,create,update,delete for every module and i put it all in the 1 role. Then, my request had rejected because the header size of request must less then 1mb.

Rules
Every 5m, you must to reclaim the permission token (base on scope) and every 15m you must to refreh the access token
You can customize the expire in config

**Comment by andrechristikan** [comment]
I got this approach from some article, github discusstion, and stackoverflow after 7daya of rnd lol.

But if you have better approach, feel free to request ☕️

**Comment by ChrisK1994** [comment]
I don't know if I get this right but why don't we just send the accessToken -> read user from Token -> check user roles -> see if roles are permitted, why is that worse?

**Comment by andrechristikan** [comment]
It releated with serverless architecture or microservice architecture
Nowdays, every service such as API Gateway from AWS have a limitation. 
One of limitation is the size.
Size of request, size of body/payload, size of headers.

If you use nginx or apache in server such as EC2 or ECS, you can change the size in their config. 
But if you use API Gateway, there has no options to change or increase the size.
So i create the permission token to decrease the access token size

FYI
AccessToken will contains role
PermissionToken will contains permission base on scope

**Comment by andrechristikan** [comment]
Maybe in your case, you can use `AuthJwtAccessProtected` for every endpoint and do not use `AuthPermissionProtected`
The AuthJwtAccessProtected decorator will only check role, and you do not need claim the permissionToken

Auth grouping decorator 
- `AuthJwtAccessProtected` for general
- `AuthJwtAdminAccessProtected` for admin.
- `AuthJwtPublicAccessProtected` for user.

**Comment by DexVN** [comment]
What if I update the permission in the database. My current permission token doesn't know this?

**Comment by andrechristikan** [comment]
Yup, you're right.
That is why the token has an expiration time.
Every time we make a change in our system (backend) that cannot be immediately implemented on the client side (because of stateless of authentication / authorization), you need to get a new token from `/login` or `/refresh` endpoints.

For the permission token, you can recreate the token from `/grant-permission` endpoint.

If your systems are monolithic applications. You can use the method that @ChrisK1994 described.
If you want to build the stateful authentication / authorization, you can use session.
It all depends on what you need.

**Comment by KLD-VN** [comment]
{
  "scope": [
    "USER",
    "ROLE",
    "PERMISSION",
    "API_KEY",
    "SETTING"
  ]
}
one more question. Is this the scope from the api?
