### ISSUE TITLE
Login/Refresh Issues

### ISSUE THREAD

**Issue by david-aimi** [andrechristikan/ack-nestjs-boilerplate-mongoose#40]
```
{
    "email":"admin@mail.com",
    "password":"aaAA@@123444",
    "rememberMe":false
}
```

login only works if rememberMe set to false, if set to true, nestjs log returning:

Sys log

`[Nest] 17068  - 03/23/2022, 8:33:34 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at AuthService.loginExpiredDate (D:\www\recipe-fork\recipefork-services\src\auth\service\auth.service.ts:132:57)
    at AuthService.createPayloadAccessToken (D:\www\recipe-fork\recipefork-services\src\auth\service\auth.service.ts:143:45)
    at AuthCommonController.login (D:\www\recipe-fork\recipefork-services\src\auth\controller\auth.common.controller.ts:123:36)`

Also, in postman, refreshToken/ {{baseUrl}}/refresh endpoint functionality does not work, and postman collection is still looking for adminRefreshToken, but that is no longer coming through login payload

**Comment by andrechristikan** [comment]
For information of the boilerplate
There have huge differences between [v0.3.0](https://github.com/andrechristikan/ack-nestjs-boilerplate-mongoose/releases/tag/v3.0.0) and [v0.2.1](https://github.com/andrechristikan/ack-nestjs-boilerplate-mongoose/releases/tag/v0.2.1)
and I suggest to you to pull the newest version

but if you already pull the newest version
I guess, the problem was you already change the value of `auth.jwt.refreshToken.expirationTime` or `auth.jwt.refreshToken.expirationTimeRememberMe` config. 
So would you like to share your config ? location in `src/config/auth.config.ts`

**Comment by andrechristikan** [comment]
I realized this is a bug when the app want to `create payload`.  The bug come if we don't set `auth.jwt.refreshToken.expirationTime or auth.jwt.refreshToken.expirationTimeRememberMe config as string with d suffix`

To fix your problem
make sure you put `auth.jwt.refreshToken.expirationTime` or `auth.jwt.refreshToken.expirationTimeRememberMe` config with suffix `d`

e.g
- 20d
- 30d
- 1d
